name: Build Develop

on:
  push:
    branches:
      - develop
      - feature/ci
    tags:
      - 'v*'

jobs:
  build:
    name: Build Application
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - uses: sparkfabrik/android-build-action@v1.0.0
        with:
          project-path: .
          output-path: resource-blocker-android.apk
